apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm-php81-bgd-alpine.fullname" . }}-contact-html
  labels:
    app: {{ template "helm-php81-bgd-alpine.name" . }}
    chart: {{ template "helm-php81-bgd-alpine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  contact.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ .Release.Name }} - Contact</title>
    </head>
    <body>
      <h1>Contact {{ template "helm-php81-bgd-alpine.name" . }}</h1>
      <p>This is the contact page for the {{ .Release.Name }} application.</p>
    </body>
    </html>
