apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm-php81-bgd-alpine.fullname" . }}-home-html
  labels:
    app: {{ template "helm-php81-bgd-alpine.name" . }}
    chart: {{ template "helm-php81-bgd-alpine.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  home.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>{{ .Release.Name }} - Home</title>
    </head>
    <body>
      <h1>Welcome to the {{ template "helm-php81-bgd-alpine.name" . }}!</h1>
      <p>This is the home page of the {{ .Release.Name }} application.</p>
    </body>
    </html>
